puts "HELLO WORLD"
puts "VERSION 1"
puts "change global config for user"
puts "add new branch"
puts "add master diff"
puts "newbranch diff"
puts "test number 2"
puts "branch2 commit"
puts "branch2 commit N2"